### ISSUE TITLE
Error with database

### ISSUE THREAD

**Issue by maxxcan** [Shirakumo/radiance-tutorial#2]
Hello,

I'm trying to make the tutorial but in the Part 2 when compile the module, say me the next error:

The variable DATABASE:CONNECTED is unbound.
   [Condition of type UNBOUND-VARIABLE]

**Comment by Shinmera** [comment]
Share your source code.

**Comment by maxxcan** [comment]
here I post my repository with the code:

https://github.com/maxxcan/radiance-tutorial/tree/master/plaster

**Comment by Shinmera** [comment]
You're missing `(in-package #:plaster)` statements at the beginning of objects.lisp and frontend.lisp.

**Comment by maxxcan** [comment]
I put the statements and the error is the same

**Comment by Shinmera** [comment]
Are you sure you're loading things correctly, as I do not get that error now.

**Comment by Shinmera** [comment]
I do not get this error with your current sources. Make sure you are loading this correctly.

**Comment by maxxcan** [comment]
ok. It's works. 
Thank you very much!
